
name: Push to server

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build SCSS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm i
    - run: npm run build
    - name: Copy files to server
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        local: "./dist/"
        remote: ${{ secrets.TARGET }}