
name: Push to server

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VUE_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      VUE_APP_MAPBOX_STYLE: ${{ secrets.MAPBOX_STYLE }}
      VUE_APP_UMAMI_KEY: ${{ secrets.VUE_APP_UMAMI_KEY }}
      VUE_APP_UMAMI_URL: ${{ secrets.VUE_APP_UMAMI_URL }}
    steps:
    - uses: actions/checkout@v4

    - name: Build Vue application
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - run: npm ci

    - run: npm run build
    
    - name: Copy files to server
      uses: garygrossgarten/github-action-scp@release
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local: "./dist/"
        remote: ${{ secrets.TARGET }}