
name: Push to server

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      VUE_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      VUE_APP_MAPBOX_STYLE: ${{ secrets.MAPBOX_STYLE }}
    steps:
    - uses: actions/checkout@master
    - name: Build Vue application
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm i
    - run: npm run build
    - name: Copy files to server
      uses: garygrossgarten/github-action-scp@release
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local: "./dist/"
        remote: ${{ secrets.TARGET }}