name: Push to server

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VUE_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      VUE_APP_MAPBOX_STYLE: ${{ secrets.MAPBOX_STYLE }}
      VUE_APP_UMAMI_KEY: ${{ secrets.VUE_APP_UMAMI_KEY }}
      VUE_APP_UMAMI_URL: ${{ secrets.VUE_APP_UMAMI_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Vue application
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - run: npm ci

      - run: npm run build

      - name: Copy files
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./dist/
          remote_path: ${{ vars.TARGET }}
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
